### ISSUE TITLE
Queued job module gets stuck

### ISSUE THREAD

**Issue by torleif** [symbiote/silverstripe-queuedjobs#84]
Running `php /path/to/silverstripe/framework/cli-script.php dev/tasks/ProcessJobQueueTask`

results in:

![screen shot 2016-02-15 at 12 51 58 pm](https://cloud.githubusercontent.com/assets/67215/13037316/022abc6e-d3e3-11e5-93d5-134c82ba9802.png)

**Comment by tractorcow** [comment]
What does the jobs CMS admin look like while running this? Are there jobs with a certain status ?

**Comment by torleif** [comment]
With the above output, there was one job with the status of 'new' and the start time in the past. the queue priory was 1.

If there is no jobs to be ran it exists as expected. The above output was on OS X.

**Comment by tractorcow** [comment]
Weird, according to that data I'd expect that job to get picked up immediately.

Which backend are you using... doorman or the legacy (default) one?

**Comment by torleif** [comment]
It looks like it only happens when the doorman one is enabled:

```
---
Name: cwpqueuedjobsconfig
Only:
  ModuleExists: queuedjobs
After: '#queuedjobsettings'
---
Injector:
  QueuedJobService:
    properties: 
      queueRunner: %$DoormanRunner
```
